name: KiKit Stuff

on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello to kikit
    steps:
      - name: Hello kikit action step
        id: hellokikit
        uses: jazzychad/PanelizePublic@v1
      # Use the output from the `hellokikit` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hellokikit.outputs.time }}"
